/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionary;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class dic_aplication extends javax.swing.JFrame {
    private boolean search_online = false;
    private boolean E_V = true;
    dictionary_EV EV = new dictionary_EV();
    dictionary_VE VE = new dictionary_VE();
    Vector<String> SearchHistory = new Vector();
    
    public dic_aplication() {
        initComponents();
        list_word();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_search = new javax.swing.JPanel();
        Button_Remove = new javax.swing.JButton();
        Button_insert = new javax.swing.JButton();
        Text_Search = new javax.swing.JTextField();
        button_search = new javax.swing.JButton();
        panel_translate = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        label_translate = new javax.swing.JLabel();
        Button_Voice = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Label_explain = new javax.swing.JLabel();
        Button_search_online = new javax.swing.JButton();
        Button_search_offline = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        List_Words = new javax.swing.JList<>();
        Button_Replace = new javax.swing.JButton();
        Button_EV = new javax.swing.JButton();
        Button_VE = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        History_List = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dictionary");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(200, 100, 1500, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panel_search.setBackground(new java.awt.Color(255, 255, 255));

        Button_Remove.setBackground(new java.awt.Color(255, 255, 255));
        Button_Remove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_Remove.setForeground(new java.awt.Color(0, 0, 102));
        Button_Remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove.jpg"))); // NOI18N
        Button_Remove.setText("Remove");
        Button_Remove.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Button_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RemoveActionPerformed(evt);
            }
        });

        Button_insert.setBackground(new java.awt.Color(255, 255, 255));
        Button_insert.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_insert.setForeground(new java.awt.Color(0, 0, 102));
        Button_insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insert.jpg"))); // NOI18N
        Button_insert.setText("Insert");
        Button_insert.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Button_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_insertActionPerformed(evt);
            }
        });

        Text_Search.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Text_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_SearchActionPerformed(evt);
            }
        });
        Text_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Text_SearchKeyReleased(evt);
            }
        });

        button_search.setBackground(new java.awt.Color(255, 255, 255));
        button_search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insert.png"))); // NOI18N
        button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_searchActionPerformed(evt);
            }
        });

        panel_translate.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        label_translate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_translate.setText("Translate to Vietnamese");

        Button_Voice.setBackground(new java.awt.Color(255, 51, 0));
        Button_Voice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images1.png"))); // NOI18N
        Button_Voice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_VoiceActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 51, 255));
        jScrollPane1.setToolTipText("");

        Label_explain.setBackground(new java.awt.Color(0, 204, 51));
        Label_explain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_explain.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane1.setViewportView(Label_explain);

        Button_search_online.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_search_online.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-google-translate-48.png"))); // NOI18N
        Button_search_online.setText("Search online");
        Button_search_online.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_search_onlineActionPerformed(evt);
            }
        });

        Button_search_offline.setBackground(new java.awt.Color(255, 255, 0));
        Button_search_offline.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_search_offline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dictionary_small.png"))); // NOI18N
        Button_search_offline.setText("Search offline");
        Button_search_offline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_search_offlineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_translate, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_search_online, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(Button_search_offline, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(Button_Voice, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_search_offline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_search_online, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(label_translate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Voice, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout panel_translateLayout = new javax.swing.GroupLayout(panel_translate);
        panel_translate.setLayout(panel_translateLayout);
        panel_translateLayout.setHorizontalGroup(
            panel_translateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_translateLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_translateLayout.setVerticalGroup(
            panel_translateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_translateLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dictionary.png"))); // NOI18N

        List_Words.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        List_Words.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        List_Words.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                List_WordsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(List_Words);

        Button_Replace.setBackground(new java.awt.Color(255, 255, 255));
        Button_Replace.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_Replace.setForeground(new java.awt.Color(0, 0, 102));
        Button_Replace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/replace.png"))); // NOI18N
        Button_Replace.setText("Replace");
        Button_Replace.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Button_Replace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ReplaceActionPerformed(evt);
            }
        });

        Button_EV.setBackground(new java.awt.Color(255, 0, 0));
        Button_EV.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Button_EV.setText("English - Việt Nam");
        Button_EV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EVActionPerformed(evt);
            }
        });

        Button_VE.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Button_VE.setText("Việt Nam - English");
        Button_VE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_VEActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("History:");

        History_List.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        History_List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        History_List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                History_ListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(History_List);

        javax.swing.GroupLayout panel_searchLayout = new javax.swing.GroupLayout(panel_search);
        panel_search.setLayout(panel_searchLayout);
        panel_searchLayout.setHorizontalGroup(
            panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_searchLayout.createSequentialGroup()
                        .addComponent(Text_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_search, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_searchLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel_searchLayout.createSequentialGroup()
                                .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_Replace, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)))
                    .addGroup(panel_searchLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Button_VE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_EV, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_translate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        panel_searchLayout.setVerticalGroup(
            panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchLayout.createSequentialGroup()
                .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_searchLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(panel_searchLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Button_EV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_VE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Text_Search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_searchLayout.createSequentialGroup()
                        .addComponent(Button_insert)
                        .addGap(18, 18, 18)
                        .addComponent(Button_Remove)
                        .addGap(18, 18, 18)
                        .addComponent(Button_Replace)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_searchLayout.createSequentialGroup()
                .addComponent(panel_translate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_search, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_search, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Hàm dịch từ được truyền vào 
     * @param word từ cần dịch nghĩa
     */
    public void TranslateWord(String word){
        if(search_online && E_V){
            Label_explain.setText(EV.TranslatebyAPI(word));
        }else if(!search_online && E_V){
            Label_explain.setText(EV.translateWordExplain(word));
        }else if(search_online && !E_V){
            Label_explain.setText(VE.TranslatebyAPI(word));
        }else{
            Label_explain.setText(VE.translateWordExplain(word));
        }
            
    }
    
    public void addSearchHistory(String word){
        SearchHistory.remove(word);
        SearchHistory.add(0,word);
        History_List.setListData(SearchHistory);
    }
    
    /**
     * xử lí sự kiện dịch từ khi ấn enter
     * @param evt biến nhận sự kiện
     */
    private void Text_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_SearchActionPerformed
        // TODO add your handling code here:
        if(Text_Search.getText() != "" || Text_Search.getText() != null)
            TranslateWord(Text_Search.getText());
        
        addSearchHistory(Text_Search.getText());
    }//GEN-LAST:event_Text_SearchActionPerformed

    /**
     * xử lí iện dịch từ khi ấn button_Search
     * @param evt biến nhận sự kiện
     */
    private void button_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_searchActionPerformed
        // TODO add your handling code here:
        if(Text_Search.getText() != "" || Text_Search.getText() != null)
            TranslateWord(Text_Search.getText());
        
        addSearchHistory(Text_Search.getText());
    }//GEN-LAST:event_button_searchActionPerformed

    /**
     * xử lí sự kiện tạo âm thanh khi ấn Button_Voice
     * @param evt biến nhận sự kiện
     */
    private void Button_VoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_VoiceActionPerformed
        // TODO add your handling code here:
       String Word = Text_Search.getText();
       if(search_online){
           if(E_V)  EV.makeVoicebyAPI(Word);
           else     VE.makeVoicebyAPI(Word);
       }else{  
           EV.makeVoice(Word);
       }
    }//GEN-LAST:event_Button_VoiceActionPerformed

    /**
     * xử lí sự kiện xóa từ khi ấn Button_Remove
     * @param evt biến nhận sự kiện
     */
    private void Button_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RemoveActionPerformed
        // TODO add your handling code here:
        Dialog_Remove dialog_Remove = new Dialog_Remove(this, rootPaneCheckingEnabled);
        
        
        dialog_Remove.setVisible(true);
        if(dialog_Remove.getWord_remove() != null)
        {
            JOptionPane.showMessageDialog(rootPane, "This word is removed.");
            if(E_V){ 
                EV.removeWord(Text_Search.getText());
                EV.keys.remove(Text_Search.getText());
            }
            else    {
                VE.removeWord(Text_Search.getText());
                VE.keys.remove(Text_Search.getText());
            }
        }
    }//GEN-LAST:event_Button_RemoveActionPerformed

    /**
     * xử lí sự kiện thay thế từ khi ấn Button_Replace
     * @param evt biến nhận sự kiện 
     */
    /**
     * hàm lưu lại file sau khi ấn nút exit
     * @param evt biến nhận sự kiện 
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        EV.overideSource();
        VE.overideSource();
    }//GEN-LAST:event_formWindowClosing

    /**
     * xử lí sự kiện thêm từ khi ấn Button_insert
     * @param evt biến nhận sự kiện 
     */
    private void Button_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_insertActionPerformed
        // TODO add your handling code here:
        Dialog_Insert dialog_Insert = new Dialog_Insert(this, rootPaneCheckingEnabled);
        dialog_Insert.setVisible(true);
        if(dialog_Insert.getNew_Word() != null && dialog_Insert.getTranslate() != null )
            if(E_V){
                EV.insertWord(dialog_Insert.getNew_Word(),dialog_Insert.getTranslate());
                EV.keys.add(dialog_Insert.getNew_Word());
            }else{
                VE.insertWord(dialog_Insert.getNew_Word(),dialog_Insert.getTranslate());
                VE.keys.add(dialog_Insert.getNew_Word());
            }
    }//GEN-LAST:event_Button_insertActionPerformed

    /**
     * hàm thay nàu Button_search_online và Button_search_offline khi ấn Button_search_online
     * @param evt biến nhận sự kiện 
     */
    private void Button_search_onlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_search_onlineActionPerformed
        // TODO add your handling code here:
        search_online = true;
        Button_search_online.setBackground(Color.YELLOW);
        Button_search_offline.setBackground(Color.LIGHT_GRAY);
        Button_Voice.setVisible(true);
    }//GEN-LAST:event_Button_search_onlineActionPerformed

    
    
    /**
     * hàm thay nàu Button_search_online và Button_search_offline khi ấn Button_search_offline
     * @param evt biến nhận sự kiện 
     */
    private void Button_search_offlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_search_offlineActionPerformed
        // TODO add your handling code here:
        search_online = false;
        Button_search_online.setBackground(Color.LIGHT_GRAY);
        Button_search_offline.setBackground(Color.YELLOW);
        if(!E_V) Button_Voice.setVisible(false);
    }//GEN-LAST:event_Button_search_offlineActionPerformed

    
    
    /**
     * xử lí dịch từ được chọn trong list_Word
     * @param evt biến nhận sự kiện 
     */
    private void List_WordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_WordsMouseClicked
        // TODO add your handling code here:
        String word = List_Words.getSelectedValue();
        Text_Search.setText(word);
        TranslateWord(Text_Search.getText());
        
        addSearchHistory(word);
                
    }//GEN-LAST:event_List_WordsMouseClicked

    /**
     * hàm thay nàu Button_EV và Button_VE khi ấn Button_VE
     * @param evt biến nhận sự kiện 
     */
    private void Button_EVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EVActionPerformed
        // TODO add your handling code here:
        Button_EV.setBackground(Color.RED);
        Button_VE.setBackground(Color.LIGHT_GRAY);
        E_V = true;
        Button_Voice.setVisible(true);
        list_word();
    }//GEN-LAST:event_Button_EVActionPerformed

    /**
     * hàm thay nàu Button_EV và Button_VE khi ấn Button_VE
     * @param evt biến nhận sự kiện 
     */
    private void Button_VEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_VEActionPerformed
        // TODO add your handling code here:
        Button_VE.setBackground(Color.RED);
        Button_EV.setBackground(Color.LIGHT_GRAY);
        E_V = false;
        if(!search_online) Button_Voice.setVisible(false);
        list_word();
    }//GEN-LAST:event_Button_VEActionPerformed
    public void list_word(){
        SearchHistory.add(" ");
        History_List.setListData(SearchHistory);
        
        DefaultListModel model1 = new DefaultListModel();
        if(E_V){
        for (int i = 0; i < EV.keys.size(); i++) {
                model1.addElement(EV.keys.get(i));
            }
        } else {
            for (int i = 0; i < VE.keys.size(); i++) {
                model1.addElement(VE.keys.get(i));
            }
        }
        List_Words.setModel(model1);
    }
    private void Text_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_SearchKeyReleased
        // TODO add your handling code here:
        ArrayList l;
            DefaultListModel model1 = new DefaultListModel();
            String word = Text_Search.getText();
            if (word.isEmpty()) {
                list_word();
            } else {
                if(E_V){
                l = EV.searchKey(word);
                } else{
                    l = VE.searchKey(word);
                }     
                for (int i = 0; i < l.size(); i++) {
                model1.addElement(l.get(i));
                }
                List_Words.setModel(model1);
            }
            
    }//GEN-LAST:event_Text_SearchKeyReleased

    private void History_ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_History_ListMouseClicked
        // TODO add your handling code here:
        String word = History_List.getSelectedValue();
        Text_Search.setText(word);
        TranslateWord(word);
    }//GEN-LAST:event_History_ListMouseClicked

    private void Button_ReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ReplaceActionPerformed
        // TODO add your handling code here:
        Dialog_Replace dialog_Replace = new Dialog_Replace(this, rootPaneCheckingEnabled);
        dialog_Replace.setVisible(true);
        if(E_V)     EV.replaceWord(dialog_Replace.getWord(), dialog_Replace.getNew_Word(), dialog_Replace.getNew_Explain());
        else        VE.replaceWord(dialog_Replace.getWord(), dialog_Replace.getNew_Word(), dialog_Replace.getNew_Explain());
    }//GEN-LAST:event_Button_ReplaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dic_aplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dic_aplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dic_aplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dic_aplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dic_aplication().setVisible(true);
            }
        });
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_EV;
    private javax.swing.JButton Button_Remove;
    private javax.swing.JButton Button_Replace;
    private javax.swing.JButton Button_VE;
    private javax.swing.JButton Button_Voice;
    private javax.swing.JButton Button_insert;
    private javax.swing.JButton Button_search_offline;
    private javax.swing.JButton Button_search_online;
    private javax.swing.JList<String> History_List;
    private javax.swing.JLabel Label_explain;
    private javax.swing.JList<String> List_Words;
    private javax.swing.JTextField Text_Search;
    private javax.swing.JButton button_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_translate;
    private javax.swing.JPanel panel_search;
    private javax.swing.JPanel panel_translate;
    // End of variables declaration//GEN-END:variables
}
